id: P006960
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD90031
  title: མའོ་ཝེན་ཆའང་རིགས་རང་སྐྱོང་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  volumes:
    24790df95b31470580a46ca4a24be08f:
      image_group_id: I1PD90106
      title: Volume 1 of mao wen qiang zu zi zhi xizn zhi
      volume_number: 1
      total_pages: 828
      base_file: v001.txt
