id: P006960
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD90031
  title: མའོ་ཝེན་ཆའང་རིགས་རང་སྐྱོང་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  volumes:
    6658659ee9894284b80f6362663f6eee:
      image_group_id: I1PD90106
      title: ''
      volume_number: 1
      total_pages: 828
ebook_metadata:
  title: མའོ་ཝེན་ཆའང་རིགས་རང་སྐྱོང་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  sku: P006960
  cover: cover.jpg
  layers:
  - pagination
