id: I8CEAF2A6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:11:33+00:00'
last_modified: '2022-06-08T12:59:34.535697+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90031
  title: མའོ་ཝེན་ཆའང་རིགས་རང་སྐྱོང་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B30D:
      image_group_id: I1PD90106
      title: Volume 1 of mao wen qiang zu zi zhi xizn zhi
      total_pages: 828
      order: 1
      base_file: B30D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
