id: I8CEAF2A6
legacy_id: P006960
ocr_import_info:
  bdrc_scan_id: W1PD90031
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T05:05:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T05:28:42.943982+00:00'
last_modified: 2022-09-01 13:29:26.234348
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD90031
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1PD90031
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: 茂汶羌族自治县志
statistics:
  ocr_word_mean_confidence_index: 0.943121299017593
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1PD90106:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD90106
      total_pages: 828
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD90106.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.943121299017593
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
